USE [master]
GO

/****** Object:  Database [RPGProject]    Script Date: 8/14/2023 7:09:58 PM ******/
CREATE DATABASE [RPGProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRGProject', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PRGProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRGProject_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PRGProject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RPGProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RPGProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RPGProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RPGProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RPGProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RPGProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [RPGProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RPGProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RPGProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RPGProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RPGProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RPGProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RPGProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RPGProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RPGProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RPGProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RPGProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RPGProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RPGProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RPGProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RPGProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RPGProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RPGProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RPGProject] SET RECOVERY FULL 
GO

ALTER DATABASE [RPGProject] SET  MULTI_USER 
GO

ALTER DATABASE [RPGProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RPGProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RPGProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RPGProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RPGProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RPGProject] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RPGProject] SET QUERY_STORE = ON
GO

ALTER DATABASE [RPGProject] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [RPGProject] SET  READ_WRITE 
GO

USE [RPGProject]
GO

/****** Object:  Table [dbo].[Class] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Class](
	[classid] [int] IDENTITY(1,1) NOT NULL,
	[classname] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Class] PRIMARY KEY CLUSTERED 
(
	[classid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Character]  ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Character](
	[charid] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[female] [bit] NOT NULL,
	[classid] [int] NOT NULL,
	FOREIGN KEY ([classid]) REFERENCES Class([classid]),
    CONSTRAINT [PK_Character] PRIMARY KEY CLUSTERED 
(
	[charid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
	
GO

/****** Object:  Table [dbo].[Stats] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Stats](
	[statsid] [int] IDENTITY(1,1) NOT NULL,
	[charid] [int] NOT NULL,
	[statname] [varchar](100) NOT NULL,
	FOREIGN KEY ([charid]) REFERENCES Character([charid]),
    CONSTRAINT [PK_Stats] PRIMARY KEY CLUSTERED 	
(
	[statsid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Saves] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Saves](
	[saveid] [int] IDENTITY(1,1) NOT NULL,
	[charid] [int] NOT NULL,
	[savename] [varchar](255) NOT NULL,
	FOREIGN KEY ([charid]) REFERENCES Character([charid]),
    CONSTRAINT [PK_Saves] PRIMARY KEY CLUSTERED 	
(
	[saveid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/******* insert classes **********/
INSERT INTO Class (classname) VALUES ('Warrior')
INSERT INTO Class (classname) VALUES ('Mage')
INSERT INTO Class (classname) VALUES ('Cleric')
INSERT INTO Class (classname) VALUES ('Bard')
INSERT INTO Class (classname) VALUES ('Hunter')
INSERT INTO Class (classname) VALUES ('Ranger')
INSERT INTO Class (classname) VALUES ('Battle Mage')
