USE [master]
GO

/****** Object:  Database [PRGProject]    Script Date: 8/14/2023 7:09:58 PM ******/
CREATE DATABASE [PRGProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRGProject', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PRGProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRGProject_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PRGProject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRGProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PRGProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PRGProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PRGProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PRGProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PRGProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [PRGProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PRGProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PRGProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PRGProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PRGProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PRGProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PRGProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PRGProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PRGProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PRGProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PRGProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PRGProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PRGProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PRGProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PRGProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PRGProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PRGProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PRGProject] SET RECOVERY FULL 
GO

ALTER DATABASE [PRGProject] SET  MULTI_USER 
GO

ALTER DATABASE [PRGProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PRGProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PRGProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PRGProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PRGProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PRGProject] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PRGProject] SET QUERY_STORE = ON
GO

ALTER DATABASE [PRGProject] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [PRGProject] SET  READ_WRITE 
GO

USE [PRGProject]
GO

/****** Object:  Table [dbo].[Character]  ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Character](
	[characterid] [int] NOT NULL,
	[name] [varchar](50) NOT NULL,
	[female] [bit] NOT NULL,
	[class] [varchar](255) NOT NULL,
	PRIMARY KEY ([characterid]));
GO

/****** Object:  Table [dbo].[Stats] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Stats](
	[statsid] [int] NOT NULL,
	[characterid] [int] NOT NULL,
	[statname] [varchar](100) NOT NULL,
	PRIMARY KEY ([statsid]),
	FOREIGN KEY ([characterid]) REFERENCES Character([characterid]));
GO